version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ecotrace_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ecotrace_network

  neo4j:
    image: neo4j:5.15.0
    container_name: ecotrace_neo4j
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - ecotrace_network

  mongodb:
    image: mongo:7.0
    container_name: ecotrace_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecotrace_network

  redis:
    image: redis:7-alpine
    container_name: ecotrace_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecotrace_network

volumes:
  elasticsearch_data:
  neo4j_data:
  neo4j_logs:
  mongodb_data:
  redis_data:

networks:
  ecotrace_network:
    driver: bridge
